# Generated by Django 6.0.2 on 2026-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
